/* Generated by cliforge — DO NOT EDIT */
#include "cmdline_trig.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* ------- internal helpers ------- */
typedef struct { const char *key; char *dst; unsigned int dstsz; } cf__kv_t;

static const char *cf__next_arg(int *i, int argc, char *const *argv)
{
	const char *arg = argv[*i];
	const char *eq  = strchr(arg, '=');
	if (eq != NULL) return eq + 1;
	if (*i + 1 < argc && argv[*i + 1][0] != '-') { (*i)++; return argv[*i]; }
	return NULL;
}

static const char trig__version[] = "trig 0.0.0";

int trig_cmdline_parse(int argc, char *const *argv,
                     struct trig_cmdline *out)
{
	int i;
	const char *arg;
	const char *val;

	(void)memset(out, 0, sizeof(*out));
	out->units = TRIG_angle_unit_RADIANS;
	out->normalize = 1;
	out->method = TRIG_trig_method_TAYLOR;

	/* --- main option parse loop --- */
	for (i = 1; i < argc; i++) {
		arg = argv[i];
		val = NULL;

		/* skip subcommand token */
		if (arg[0] != '-') continue;

		/* --help */
		if (strcmp(arg, "--help") == 0 || strcmp(arg, "-h") == 0) {
			trig_cmdline_help();
			return 1;
		}
		/* --version */
		if (strcmp(arg, "--version") == 0) {
			trig_cmdline_version();
			return 1;
		}

		if (strncmp(arg, "--units", 7) == 0 &&
		    (arg[7] == '\0' || arg[7] == '=')) {
			val = cf__next_arg(&i, argc, argv);
			if (!val) { fprintf(stderr, "error: --units requires argument\n"); return -1; }
			if (strcmp(val, "radians") == 0) out->units = TRIG_angle_unit_RADIANS;
			else if (strcmp(val, "degrees") == 0) out->units = TRIG_angle_unit_DEGREES;
			else if (strcmp(val, "gradians") == 0) out->units = TRIG_angle_unit_GRADIANS;
			else if (strcmp(val, "turns") == 0) out->units = TRIG_angle_unit_TURNS;
			else { fprintf(stderr, "error: invalid value for --units: %s\n", val); return -1; }
			continue;
		}
		if (strcmp(arg, "-u") == 0) {
			val = cf__next_arg(&i, argc, argv);
			if (!val) { fprintf(stderr, "error: --units requires argument\n"); return -1; }
			if (strcmp(val, "radians") == 0) out->units = TRIG_angle_unit_RADIANS;
			else if (strcmp(val, "degrees") == 0) out->units = TRIG_angle_unit_DEGREES;
			else if (strcmp(val, "gradians") == 0) out->units = TRIG_angle_unit_GRADIANS;
			else if (strcmp(val, "turns") == 0) out->units = TRIG_angle_unit_TURNS;
			else { fprintf(stderr, "error: invalid value for --units: %s\n", val); return -1; }
			continue;
		}
		if (strncmp(arg, "--normalize", 11) == 0 &&
		    (arg[11] == '\0' || arg[11] == '=')) {
			val = cf__next_arg(&i, argc, argv);
			if (!val) { fprintf(stderr, "error: --normalize requires argument\n"); return -1; }
			out->normalize = (strcmp(val,"true")==0||strcmp(val,"yes")==0||
			           strcmp(val,"on")==0||strcmp(val,"1")==0) ? 1 : 0;
			continue;
		}
		if (strncmp(arg, "--method", 8) == 0 &&
		    (arg[8] == '\0' || arg[8] == '=')) {
			val = cf__next_arg(&i, argc, argv);
			if (!val) { fprintf(stderr, "error: --method requires argument\n"); return -1; }
			if (strcmp(val, "taylor") == 0) out->method = TRIG_trig_method_TAYLOR;
			else if (strcmp(val, "cordic") == 0) out->method = TRIG_trig_method_CORDIC;
			else if (strcmp(val, "lookup") == 0) out->method = TRIG_trig_method_LOOKUP;
			else { fprintf(stderr, "error: invalid value for --method: %s\n", val); return -1; }
			continue;
		}
		/* pass-through: --namespace.option for dlopen plugins */
		if (arg[0]=='-' && arg[1]=='-' && strchr(arg+2,'.')!=NULL) { continue; }
		/* positional or unknown option */
		if (arg[0] == '-') {
			fprintf(stderr, "error: unknown option: %s\n", arg);
			return -1;
		}
	}

	return 0;
}

void trig_cmdline_help(void)
{
	fputs("Usage: trig [OPTIONS]\n", stdout);
	fputs("Trigonometric ops (sin, cos, tan, asin, acos, atan2, ...)\n", stdout);
	fputs("\nOptions:\n", stdout);
	fputs("\n  Angles:\n", stdout);
	fputs("  -u, --units                ENUM     Unit used to interpret arguments to trig functions.  [default: radians]\n", stdout);
	fputs("      --normalize            BOOL     Reduce input angle modulo 2π before evaluation.  [default: on]\n", stdout);
	fputs("      --help                          Show this help\n", stdout);
	fputs("      --version                       Show version\n", stdout);
}

void trig_cmdline_version(void)
{
	fprintf(stdout, "%s\n", trig__version);
}

void trig_cmdline_dump(const struct trig_cmdline *args)
{
	fprintf(stdout, "units=%ld\n", (long)args->units);
	fprintf(stdout, "normalize=%d\n", args->normalize);
	fprintf(stdout, "method=%ld\n", (long)args->method);
}
