/* Generated by cliforge — DO NOT EDIT */
#ifndef TRIG_CMDLINE_H
#define TRIG_CMDLINE_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>

typedef enum trig_angle_unit {
	TRIG_angle_unit_RADIANS = 0,
	TRIG_angle_unit_DEGREES = 1,
	TRIG_angle_unit_GRADIANS = 2,
	TRIG_angle_unit_TURNS = 3
} trig_angle_unit_t;

typedef enum trig_trig_method {
	TRIG_trig_method_TAYLOR = 0,
	TRIG_trig_method_CORDIC = 1,
	TRIG_trig_method_LOOKUP = 2
} trig_trig_method_t;

struct trig_cmdline {
	trig_angle_unit_t	units;
	int	normalize;
	trig_trig_method_t	method;
};

int  trig_cmdline_parse(int argc, char *const *argv,
                      struct trig_cmdline *out);
void trig_cmdline_help(void);
void trig_cmdline_version(void);
void trig_cmdline_dump(const struct trig_cmdline *args);

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* TRIG_CMDLINE_H */
