/* Generated by cliforge — DO NOT EDIT */
#ifndef OL_CMDLINE_H
#define OL_CMDLINE_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>

typedef enum ol_backend_type {
	OL_backend_type_NAIVE = 0,
	OL_backend_type_BLAS = 1
} ol_backend_type_t;

struct ol_cmdline {
	uint8_t	precision;
	ol_backend_type_t	backend;
	uint64_t	cache_size;
	uint64_t	cache_ttl;
};

int  ol_cmdline_parse(int argc, char *const *argv,
                      struct ol_cmdline *out);
void ol_cmdline_help(void);
void ol_cmdline_version(void);
void ol_cmdline_dump(const struct ol_cmdline *args);

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* OL_CMDLINE_H */
