/* Generated by cliforge — DO NOT EDIT */
#include "cmdline_ops_linear.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* ------- internal helpers ------- */
typedef struct { const char *key; char *dst; unsigned int dstsz; } cf__kv_t;

static const char *cf__next_arg(int *i, int argc, char *const *argv)
{
	const char *arg = argv[*i];
	const char *eq  = strchr(arg, '=');
	if (eq != NULL) return eq + 1;
	if (*i + 1 < argc && argv[*i + 1][0] != '-') { (*i)++; return argv[*i]; }
	return NULL;
}

static const char ol__version[] = "ops_linear 0.1.0";

int ol_cmdline_parse(int argc, char *const *argv,
                     struct ol_cmdline *out)
{
	int i;
	const char *arg;
	const char *val;

	(void)memset(out, 0, sizeof(*out));
	out->precision = 10; /* 10 */
	out->backend = OL_backend_type_NAIVE;
	out->cache_size = 0; /* 0 */
	out->cache_ttl = 0; /* 0ms */

	/* --- main option parse loop --- */
	for (i = 1; i < argc; i++) {
		arg = argv[i];
		val = NULL;

		/* skip subcommand token */
		if (arg[0] != '-') continue;

		/* --help */
		if (strcmp(arg, "--help") == 0 || strcmp(arg, "-h") == 0) {
			ol_cmdline_help();
			return 1;
		}
		/* --version */
		if (strcmp(arg, "--version") == 0) {
			ol_cmdline_version();
			return 1;
		}

		if (strncmp(arg, "--precision", 11) == 0 &&
		    (arg[11] == '\0' || arg[11] == '=')) {
			val = cf__next_arg(&i, argc, argv);
			if (!val) { fprintf(stderr, "error: --precision requires argument\n"); return -1; }
			out->precision = (uint8_t)strtoul(val, NULL, 0);
			continue;
		}
		if (strncmp(arg, "--backend", 9) == 0 &&
		    (arg[9] == '\0' || arg[9] == '=')) {
			val = cf__next_arg(&i, argc, argv);
			if (!val) { fprintf(stderr, "error: --backend requires argument\n"); return -1; }
			if (strcmp(val, "naive") == 0) out->backend = OL_backend_type_NAIVE;
			else if (strcmp(val, "blas") == 0) out->backend = OL_backend_type_BLAS;
			else { fprintf(stderr, "error: invalid value for --backend: %s\n", val); return -1; }
			continue;
		}
		if (strncmp(arg, "--cache-size", 12) == 0 &&
		    (arg[12] == '\0' || arg[12] == '=')) {
			val = cf__next_arg(&i, argc, argv);
			if (!val) { fprintf(stderr, "error: --cache-size requires argument\n"); return -1; }
			out->cache_size = (uint64_t)strtoul(val, NULL, 0);
			continue;
		}
		if (strncmp(arg, "--cache-ttl", 11) == 0 &&
		    (arg[11] == '\0' || arg[11] == '=')) {
			val = cf__next_arg(&i, argc, argv);
			if (!val) { fprintf(stderr, "error: --cache-ttl requires argument\n"); return -1; }
			out->cache_ttl = (uint64_t)strtoul(val, NULL, 0);
			continue;
		}
		/* pass-through: --namespace.option for dlopen plugins */
		if (arg[0]=='-' && arg[1]=='-' && strchr(arg+2,'.')!=NULL) { continue; }
		/* positional or unknown option */
		if (arg[0] == '-') {
			fprintf(stderr, "error: unknown option: %s\n", arg);
			return -1;
		}
	}

	return 0;
}

void ol_cmdline_help(void)
{
	fputs("Usage: ops_linear [OPTIONS]\n", stdout);
	fputs("Linear-algebra operator plugin (dot, norm, mat-vec)\n", stdout);
	fputs("\nOptions:\n", stdout);
	fputs("\n  Computation:\n", stdout);
	fputs("      --precision            UINT8    Decimal digits of precision for intermediate accumulation.  [default: 10]\n", stdout);
	fputs("      --backend              ENUM     Computation backend: naive (portable C) or blas (requires BLAS at runtime).  [default: naive]\n", stdout);
	fputs("\n  Cache:\n", stdout);
	fputs("      --cache-size           BYTES    Size of the LRU result cache (0 = disabled).  [default: 0]\n", stdout);
	fputs("      --cache-ttl            TIME     Cache entry lifetime (0 = never evict).  [default: 0ms]\n", stdout);
	fputs("      --help                          Show this help\n", stdout);
	fputs("      --version                       Show version\n", stdout);
}

void ol_cmdline_version(void)
{
	fprintf(stdout, "%s\n", ol__version);
}

void ol_cmdline_dump(const struct ol_cmdline *args)
{
	fprintf(stdout, "precision=%ld\n", (long)args->precision);
	fprintf(stdout, "backend=%ld\n", (long)args->backend);
	fprintf(stdout, "cache-size=%ld\n", (long)args->cache_size);
	fprintf(stdout, "cache-ttl=%ld\n", (long)args->cache_ttl);
}
