/* Generated by cliforge — DO NOT EDIT */
#include "cmdline_cmp.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* ------- internal helpers ------- */
typedef struct { const char *key; char *dst; unsigned int dstsz; } cf__kv_t;

static const char *cf__next_arg(int *i, int argc, char *const *argv)
{
	const char *arg = argv[*i];
	const char *eq  = strchr(arg, '=');
	if (eq != NULL) return eq + 1;
	if (*i + 1 < argc && argv[*i + 1][0] != '-') { (*i)++; return argv[*i]; }
	return NULL;
}

static const char cmp__version[] = "cmp 0.0.0";

int cmp_cmdline_parse(int argc, char *const *argv,
                     struct cmp_cmdline *out)
{
	int i;
	const char *arg;
	const char *val;

	(void)memset(out, 0, sizeof(*out));
	out->epsilon = 1.0e-12;
	out->nan_equal = 0;

	/* --- main option parse loop --- */
	for (i = 1; i < argc; i++) {
		arg = argv[i];
		val = NULL;

		/* skip subcommand token */
		if (arg[0] != '-') continue;

		/* --help */
		if (strcmp(arg, "--help") == 0 || strcmp(arg, "-h") == 0) {
			cmp_cmdline_help();
			return 1;
		}
		/* --version */
		if (strcmp(arg, "--version") == 0) {
			cmp_cmdline_version();
			return 1;
		}

		if (strncmp(arg, "--epsilon", 9) == 0 &&
		    (arg[9] == '\0' || arg[9] == '=')) {
			val = cf__next_arg(&i, argc, argv);
			if (!val) { fprintf(stderr, "error: --epsilon requires argument\n"); return -1; }
			out->epsilon = strtod(val, NULL);
			continue;
		}
		if (strncmp(arg, "--nan-equal", 11) == 0 &&
		    (arg[11] == '\0' || arg[11] == '=')) {
			val = cf__next_arg(&i, argc, argv);
			if (!val) { fprintf(stderr, "error: --nan-equal requires argument\n"); return -1; }
			out->nan_equal = (strcmp(val,"true")==0||strcmp(val,"yes")==0||
			           strcmp(val,"on")==0||strcmp(val,"1")==0) ? 1 : 0;
			continue;
		}
		/* pass-through: --namespace.option for dlopen plugins */
		if (arg[0]=='-' && arg[1]=='-' && strchr(arg+2,'.')!=NULL) { continue; }
		/* positional or unknown option */
		if (arg[0] == '-') {
			fprintf(stderr, "error: unknown option: %s\n", arg);
			return -1;
		}
	}

	return 0;
}

void cmp_cmdline_help(void)
{
	fputs("Usage: cmp [OPTIONS]\n", stdout);
	fputs("Comparison operators (<, >, ==, !=, <=, >=)\n", stdout);
	fputs("\nOptions:\n", stdout);
	fputs("\n  Comparison:\n", stdout);
	fputs("      --epsilon              DOUBLE   Floating-point comparison tolerance.  [default: 1.0e-12]\n", stdout);
	fputs("      --nan-equal            BOOL     Treat NaN as equal to itself for the == operator.  [default: off]\n", stdout);
	fputs("      --help                          Show this help\n", stdout);
	fputs("      --version                       Show version\n", stdout);
}

void cmp_cmdline_version(void)
{
	fprintf(stdout, "%s\n", cmp__version);
}

void cmp_cmdline_dump(const struct cmp_cmdline *args)
{
	fprintf(stdout, "epsilon=%g\n", args->epsilon);
	fprintf(stdout, "nan-equal=%d\n", args->nan_equal);
}
