/* Generated by cliforge — DO NOT EDIT */
#ifndef CMP_CMDLINE_H
#define CMP_CMDLINE_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>

struct cmp_cmdline {
	double	epsilon;
	int	nan_equal;
};

int  cmp_cmdline_parse(int argc, char *const *argv,
                      struct cmp_cmdline *out);
void cmp_cmdline_help(void);
void cmp_cmdline_version(void);
void cmp_cmdline_dump(const struct cmp_cmdline *args);

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* CMP_CMDLINE_H */
