/* Generated by cliforge — DO NOT EDIT */
#include "cmdline.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* ------- internal helpers ------- */
typedef struct { const char *key; char *dst; unsigned int dstsz; } cf__kv_t;

static const char *cf__next_arg(int *i, int argc, char *const *argv)
{
	const char *arg = argv[*i];
	const char *eq  = strchr(arg, '=');
	if (eq != NULL) return eq + 1;
	if (*i + 1 < argc && argv[*i + 1][0] != '-') { (*i)++; return argv[*i]; }
	return NULL;
}

static void cf__parse_compound(const char *s, cf__kv_t *fields, unsigned int nfields)
{
	char buf[4096];
	char *tok;
	unsigned int fi;
	(void)strncpy(buf, s, sizeof(buf) - 1U);
	tok = strtok(buf, ",");
	while (tok != NULL) {
		char *eq = strchr(tok, '=');
		if (eq != NULL) {
			*eq = '\0';
			for (fi = 0U; fi < nfields; fi++) {
				if (strcmp(tok, fields[fi].key) == 0) {
					(void)strncpy(fields[fi].dst, eq + 1, fields[fi].dstsz - 1U);
					break;
				}
			}
		}
		tok = strtok(NULL, ",");
	}
}

static const char cc__version[] = "calctool 0.2.0";

int cc_cmdline_parse(int argc, char *const *argv,
                     struct cc_cmdline *out)
{
	int i;
	const char *arg;
	const char *val;

	(void)memset(out, 0, sizeof(*out));
	out->extended_precision = 0;
	out->angle_unit = 0; /* default: radians */
	out->precision = 12; /* 12 */
	out->mode = CC_eval_mode_REAL;
	out->verbosity = CC_verbosity_NORMAL;
	(void)strncpy(out->logfile, "./calctool.log", sizeof(out->logfile) - 1U);
	(void)strncpy(out->work_dir, ".", sizeof(out->work_dir) - 1U);
	out->no_prompt = 0;
	(void)strncpy(out->locale, "C", sizeof(out->locale) - 1U);
	out->nice = 0;
	out->rpc_port = 9000;
	out->seed = -1;
	out->byte_offset = 0;
	out->max_vars = 256; /* 256 */
	out->max_steps = 1000000; /* 1_000_000 */
	out->feature_flags = 0; /* 0x0 */
	out->progress_interval = 0.5;
	out->epsilon = 1e-9;
	(void)strncpy(out->api_url, "https://api.example.com", sizeof(out->api_url) - 1U);
	out->format = CC_output_fmt_TEXT;
	out->color = 0;
	out->encoding = 0; /* default: utf8 */
	(void)strncpy(out->syslog_tag, "calctool", sizeof(out->syslog_tag) - 1U);
	out->deadline = 250; /* 250ms */
	out->stack = 1; /* 1MiB */
	out->memory_budget = 256; /* 256MiB */
	out->sample_rate = 1; /* 1kHz */
	out->gc_threshold = 75; /* 75% */
	(void)strncpy(out->plugin_path, "./plugins", sizeof(out->plugin_path) - 1U);
	out->no_sandbox = 0;
	out->plugin_abi = 0; /* default: auto */
	out->workers = 4; /* 4 */
	out->thread_sched = CC_sched_pol_SCHED_OTHER;
	out->thread_prio = 50; /* 50 */
	out->cpu_mask = 0; /* 0xFFFF */

	/* --- subcommand detection --- */
	for (i = 1; i < argc; i++) {
		arg = argv[i];
		if (arg[0] == '-') continue; /* skip option arguments */
		if (strcmp(arg, "eval") == 0) { out->subcmd = CC_CMD_EVAL; break; }
		else if (strcmp(arg, "bench") == 0) { out->subcmd = CC_CMD_BENCH; break; }
		else if (strcmp(arg, "evaluate") == 0) { out->subcmd = CC_CMD_EVALUATE; break; }
	}

	/* --- main option parse loop --- */
	for (i = 1; i < argc; i++) {
		arg = argv[i];
		val = NULL;

		/* skip subcommand token */
		if (arg[0] != '-') continue;

		/* --help */
		if (strcmp(arg, "--help") == 0 || strcmp(arg, "-h") == 0) {
			cc_cmdline_help();
			return 1;
		}
		/* --version */
		if (strcmp(arg, "--version") == 0) {
			cc_cmdline_version();
			return 1;
		}

		if (strncmp(arg, "--crypto-key", 12) == 0 &&
		    (arg[12] == '\0' || arg[12] == '=')) {
			val = cf__next_arg(&i, argc, argv);
			if (!val) { fprintf(stderr, "error: --crypto-key requires argument\n"); return -1; }
			(void)strncpy(out->crypto_key, val, sizeof(out->crypto_key) - 1U);
			continue;
		}
		if (strncmp(arg, "--extended-precision", 20) == 0 &&
		    (arg[20] == '\0' || arg[20] == '=')) {
			val = cf__next_arg(&i, argc, argv);
			if (!val) { fprintf(stderr, "error: --extended-precision requires argument\n"); return -1; }
			out->extended_precision = (strcmp(val,"true")==0||strcmp(val,"yes")==0||
			           strcmp(val,"on")==0||strcmp(val,"1")==0) ? 1 : 0;
			continue;
		}
		if (strncmp(arg, "--angle-unit", 12) == 0 &&
		    (arg[12] == '\0' || arg[12] == '=')) {
			val = cf__next_arg(&i, argc, argv);
			if (!val) { fprintf(stderr, "error: --angle-unit requires argument\n"); return -1; }
			out->angle_unit = (int)strtol(val, NULL, 0);
			continue;
		}
		if (strcmp(arg, "-a") == 0) {
			val = cf__next_arg(&i, argc, argv);
			if (!val) { fprintf(stderr, "error: --angle-unit requires argument\n"); return -1; }
			out->angle_unit = (int)strtol(val, NULL, 0);
			continue;
		}
		if (strncmp(arg, "--debug-asm", 11) == 0 &&
		    (arg[11] == '\0' || arg[11] == '=')) {
			out->debug_asm = 1;
			continue;
		}
		if (strncmp(arg, "--precision", 11) == 0 &&
		    (arg[11] == '\0' || arg[11] == '=')) {
			val = cf__next_arg(&i, argc, argv);
			if (!val) { fprintf(stderr, "error: --precision requires argument\n"); return -1; }
			out->precision = (uint8_t)strtoul(val, NULL, 0);
			continue;
		}
		if (strcmp(arg, "-p") == 0) {
			val = cf__next_arg(&i, argc, argv);
			if (!val) { fprintf(stderr, "error: --precision requires argument\n"); return -1; }
			out->precision = (uint8_t)strtoul(val, NULL, 0);
			continue;
		}
		if (strncmp(arg, "--mode", 6) == 0 &&
		    (arg[6] == '\0' || arg[6] == '=')) {
			val = cf__next_arg(&i, argc, argv);
			if (!val) { fprintf(stderr, "error: --mode requires argument\n"); return -1; }
			if (strcmp(val, "integer") == 0) out->mode = CC_eval_mode_INTEGER;
			else if (strcmp(val, "real") == 0) out->mode = CC_eval_mode_REAL;
			else if (strcmp(val, "complex") == 0) out->mode = CC_eval_mode_COMPLEX;
			else { fprintf(stderr, "error: invalid value for --mode: %s\n", val); return -1; }
			continue;
		}
		if (strcmp(arg, "-m") == 0) {
			val = cf__next_arg(&i, argc, argv);
			if (!val) { fprintf(stderr, "error: --mode requires argument\n"); return -1; }
			if (strcmp(val, "integer") == 0) out->mode = CC_eval_mode_INTEGER;
			else if (strcmp(val, "real") == 0) out->mode = CC_eval_mode_REAL;
			else if (strcmp(val, "complex") == 0) out->mode = CC_eval_mode_COMPLEX;
			else { fprintf(stderr, "error: invalid value for --mode: %s\n", val); return -1; }
			continue;
		}
		if (strncmp(arg, "--verbosity", 11) == 0 &&
		    (arg[11] == '\0' || arg[11] == '=')) {
			val = cf__next_arg(&i, argc, argv);
			if (!val) { fprintf(stderr, "error: --verbosity requires argument\n"); return -1; }
			if (strcmp(val, "quiet") == 0) out->verbosity = CC_verbosity_QUIET;
			else if (strcmp(val, "normal") == 0) out->verbosity = CC_verbosity_NORMAL;
			else if (strcmp(val, "verbose") == 0) out->verbosity = CC_verbosity_VERBOSE;
			else if (strcmp(val, "trace") == 0) out->verbosity = CC_verbosity_TRACE;
			else { fprintf(stderr, "error: invalid value for --verbosity: %s\n", val); return -1; }
			continue;
		}
		if (strcmp(arg, "-v") == 0) {
			val = cf__next_arg(&i, argc, argv);
			if (!val) { fprintf(stderr, "error: --verbosity requires argument\n"); return -1; }
			if (strcmp(val, "quiet") == 0) out->verbosity = CC_verbosity_QUIET;
			else if (strcmp(val, "normal") == 0) out->verbosity = CC_verbosity_NORMAL;
			else if (strcmp(val, "verbose") == 0) out->verbosity = CC_verbosity_VERBOSE;
			else if (strcmp(val, "trace") == 0) out->verbosity = CC_verbosity_TRACE;
			else { fprintf(stderr, "error: invalid value for --verbosity: %s\n", val); return -1; }
			continue;
		}
		if (strncmp(arg, "--logfile", 9) == 0 &&
		    (arg[9] == '\0' || arg[9] == '=')) {
			val = cf__next_arg(&i, argc, argv);
			if (!val) { fprintf(stderr, "error: --logfile requires argument\n"); return -1; }
			(void)strncpy(out->logfile, val, sizeof(out->logfile) - 1U);
			continue;
		}
		if (strcmp(arg, "-l") == 0) {
			val = cf__next_arg(&i, argc, argv);
			if (!val) { fprintf(stderr, "error: --logfile requires argument\n"); return -1; }
			(void)strncpy(out->logfile, val, sizeof(out->logfile) - 1U);
			continue;
		}
		if (strncmp(arg, "--work-dir", 10) == 0 &&
		    (arg[10] == '\0' || arg[10] == '=')) {
			val = cf__next_arg(&i, argc, argv);
			if (!val) { fprintf(stderr, "error: --work-dir requires argument\n"); return -1; }
			(void)strncpy(out->work_dir, val, sizeof(out->work_dir) - 1U);
			continue;
		}
		if (strcmp(arg, "-W") == 0) {
			val = cf__next_arg(&i, argc, argv);
			if (!val) { fprintf(stderr, "error: --work-dir requires argument\n"); return -1; }
			(void)strncpy(out->work_dir, val, sizeof(out->work_dir) - 1U);
			continue;
		}
		if (strncmp(arg, "--config-file", 13) == 0 &&
		    (arg[13] == '\0' || arg[13] == '=')) {
			val = cf__next_arg(&i, argc, argv);
			if (!val) { fprintf(stderr, "error: --config-file requires argument\n"); return -1; }
			(void)strncpy(out->config_file, val, sizeof(out->config_file) - 1U);
			continue;
		}
		if (strcmp(arg, "-C") == 0) {
			val = cf__next_arg(&i, argc, argv);
			if (!val) { fprintf(stderr, "error: --config-file requires argument\n"); return -1; }
			(void)strncpy(out->config_file, val, sizeof(out->config_file) - 1U);
			continue;
		}
		if (strncmp(arg, "--no-prompt", 11) == 0 &&
		    (arg[11] == '\0' || arg[11] == '=')) {
			val = cf__next_arg(&i, argc, argv);
			if (!val) { fprintf(stderr, "error: --no-prompt requires argument\n"); return -1; }
			out->no_prompt = (strcmp(val,"true")==0||strcmp(val,"yes")==0||
			           strcmp(val,"on")==0||strcmp(val,"1")==0) ? 1 : 0;
			continue;
		}
		if (strncmp(arg, "--locale", 8) == 0 &&
		    (arg[8] == '\0' || arg[8] == '=')) {
			val = cf__next_arg(&i, argc, argv);
			if (!val) { fprintf(stderr, "error: --locale requires argument\n"); return -1; }
			(void)strncpy(out->locale, val, sizeof(out->locale) - 1U);
			continue;
		}
		if (strncmp(arg, "--nice", 6) == 0 &&
		    (arg[6] == '\0' || arg[6] == '=')) {
			val = cf__next_arg(&i, argc, argv);
			if (!val) { fprintf(stderr, "error: --nice requires argument\n"); return -1; }
			out->nice = (int8_t)strtol(val, NULL, 0);
			continue;
		}
		if (strncmp(arg, "--rpc-port", 10) == 0 &&
		    (arg[10] == '\0' || arg[10] == '=')) {
			val = cf__next_arg(&i, argc, argv);
			if (!val) { fprintf(stderr, "error: --rpc-port requires argument\n"); return -1; }
			out->rpc_port = (int16_t)strtol(val, NULL, 0);
			continue;
		}
		if (strncmp(arg, "--seed", 6) == 0 &&
		    (arg[6] == '\0' || arg[6] == '=')) {
			val = cf__next_arg(&i, argc, argv);
			if (!val) { fprintf(stderr, "error: --seed requires argument\n"); return -1; }
			out->seed = (int32_t)strtol(val, NULL, 0);
			continue;
		}
		if (strncmp(arg, "--byte-offset", 13) == 0 &&
		    (arg[13] == '\0' || arg[13] == '=')) {
			val = cf__next_arg(&i, argc, argv);
			if (!val) { fprintf(stderr, "error: --byte-offset requires argument\n"); return -1; }
			out->byte_offset = (int64_t)strtol(val, NULL, 0);
			continue;
		}
		if (strncmp(arg, "--max-vars", 10) == 0 &&
		    (arg[10] == '\0' || arg[10] == '=')) {
			val = cf__next_arg(&i, argc, argv);
			if (!val) { fprintf(stderr, "error: --max-vars requires argument\n"); return -1; }
			out->max_vars = (uint16_t)strtoul(val, NULL, 0);
			continue;
		}
		if (strncmp(arg, "--max-steps", 11) == 0 &&
		    (arg[11] == '\0' || arg[11] == '=')) {
			val = cf__next_arg(&i, argc, argv);
			if (!val) { fprintf(stderr, "error: --max-steps requires argument\n"); return -1; }
			out->max_steps = (uint32_t)strtoul(val, NULL, 0);
			continue;
		}
		if (strncmp(arg, "--feature-flags", 15) == 0 &&
		    (arg[15] == '\0' || arg[15] == '=')) {
			val = cf__next_arg(&i, argc, argv);
			if (!val) { fprintf(stderr, "error: --feature-flags requires argument\n"); return -1; }
			out->feature_flags = (uint64_t)strtoul(val, NULL, 0);
			continue;
		}
		if (strncmp(arg, "--progress-interval", 19) == 0 &&
		    (arg[19] == '\0' || arg[19] == '=')) {
			val = cf__next_arg(&i, argc, argv);
			if (!val) { fprintf(stderr, "error: --progress-interval requires argument\n"); return -1; }
			out->progress_interval = (float)strtod(val, NULL);
			continue;
		}
		if (strncmp(arg, "--epsilon", 9) == 0 &&
		    (arg[9] == '\0' || arg[9] == '=')) {
			val = cf__next_arg(&i, argc, argv);
			if (!val) { fprintf(stderr, "error: --epsilon requires argument\n"); return -1; }
			out->epsilon = strtod(val, NULL);
			continue;
		}
		if (strncmp(arg, "--api-token", 11) == 0 &&
		    (arg[11] == '\0' || arg[11] == '=')) {
			val = cf__next_arg(&i, argc, argv);
			if (!val) { fprintf(stderr, "error: --api-token requires argument\n"); return -1; }
			(void)strncpy(out->api_token, val, sizeof(out->api_token) - 1U);
			continue;
		}
		if (strncmp(arg, "--api-url", 9) == 0 &&
		    (arg[9] == '\0' || arg[9] == '=')) {
			val = cf__next_arg(&i, argc, argv);
			if (!val) { fprintf(stderr, "error: --api-url requires argument\n"); return -1; }
			(void)strncpy(out->api_url, val, sizeof(out->api_url) - 1U);
			continue;
		}
		if (strncmp(arg, "--old-mode", 10) == 0 &&
		    (arg[10] == '\0' || arg[10] == '=')) {
			val = cf__next_arg(&i, argc, argv);
			if (!val) { fprintf(stderr, "error: --old-mode requires argument\n"); return -1; }
			(void)strncpy(out->old_mode, val, sizeof(out->old_mode) - 1U);
			continue;
		}
		if (strncmp(arg, "--format", 8) == 0 &&
		    (arg[8] == '\0' || arg[8] == '=')) {
			val = cf__next_arg(&i, argc, argv);
			if (!val) { fprintf(stderr, "error: --format requires argument\n"); return -1; }
			if (strcmp(val, "text") == 0) out->format = CC_output_fmt_TEXT;
			else if (strcmp(val, "json") == 0) out->format = CC_output_fmt_JSON;
			else if (strcmp(val, "csv") == 0) out->format = CC_output_fmt_CSV;
			else if (strcmp(val, "binary") == 0) out->format = CC_output_fmt_BINARY;
			else { fprintf(stderr, "error: invalid value for --format: %s\n", val); return -1; }
			continue;
		}
		if (strcmp(arg, "-F") == 0) {
			val = cf__next_arg(&i, argc, argv);
			if (!val) { fprintf(stderr, "error: --format requires argument\n"); return -1; }
			if (strcmp(val, "text") == 0) out->format = CC_output_fmt_TEXT;
			else if (strcmp(val, "json") == 0) out->format = CC_output_fmt_JSON;
			else if (strcmp(val, "csv") == 0) out->format = CC_output_fmt_CSV;
			else if (strcmp(val, "binary") == 0) out->format = CC_output_fmt_BINARY;
			else { fprintf(stderr, "error: invalid value for --format: %s\n", val); return -1; }
			continue;
		}
		if (strncmp(arg, "--color", 7) == 0 &&
		    (arg[7] == '\0' || arg[7] == '=')) {
			val = cf__next_arg(&i, argc, argv);
			if (!val) { fprintf(stderr, "error: --color requires argument\n"); return -1; }
			out->color = (strcmp(val,"true")==0||strcmp(val,"yes")==0||
			           strcmp(val,"on")==0||strcmp(val,"1")==0) ? 1 : 0;
			continue;
		}
		if (strcmp(arg, "-c") == 0) {
			val = cf__next_arg(&i, argc, argv);
			if (!val) { fprintf(stderr, "error: --color requires argument\n"); return -1; }
			out->color = (strcmp(val,"true")==0||strcmp(val,"yes")==0||
			           strcmp(val,"on")==0||strcmp(val,"1")==0) ? 1 : 0;
			continue;
		}
		if (strncmp(arg, "--json", 6) == 0 &&
		    (arg[6] == '\0' || arg[6] == '=')) {
			out->json = 1;
			continue;
		}
		if (strcmp(arg, "-j") == 0) {
			out->json = 1;
			continue;
		}
		if (strncmp(arg, "--outfile", 9) == 0 &&
		    (arg[9] == '\0' || arg[9] == '=')) {
			val = cf__next_arg(&i, argc, argv);
			if (!val) { fprintf(stderr, "error: --outfile requires argument\n"); return -1; }
			(void)strncpy(out->outfile, val, sizeof(out->outfile) - 1U);
			continue;
		}
		if (strcmp(arg, "-o") == 0) {
			val = cf__next_arg(&i, argc, argv);
			if (!val) { fprintf(stderr, "error: --outfile requires argument\n"); return -1; }
			(void)strncpy(out->outfile, val, sizeof(out->outfile) - 1U);
			continue;
		}
		if (strncmp(arg, "--encoding", 10) == 0 &&
		    (arg[10] == '\0' || arg[10] == '=')) {
			val = cf__next_arg(&i, argc, argv);
			if (!val) { fprintf(stderr, "error: --encoding requires argument\n"); return -1; }
			out->encoding = (int)strtol(val, NULL, 0);
			continue;
		}
		if (strncmp(arg, "--syslog-tag", 12) == 0 &&
		    (arg[12] == '\0' || arg[12] == '=')) {
			val = cf__next_arg(&i, argc, argv);
			if (!val) { fprintf(stderr, "error: --syslog-tag requires argument\n"); return -1; }
			(void)strncpy(out->syslog_tag, val, sizeof(out->syslog_tag) - 1U);
			continue;
		}
		if (strncmp(arg, "--deadline", 10) == 0 &&
		    (arg[10] == '\0' || arg[10] == '=')) {
			val = cf__next_arg(&i, argc, argv);
			if (!val) { fprintf(stderr, "error: --deadline requires argument\n"); return -1; }
			out->deadline = (uint64_t)strtoul(val, NULL, 0);
			continue;
		}
		if (strncmp(arg, "--stack", 7) == 0 &&
		    (arg[7] == '\0' || arg[7] == '=')) {
			val = cf__next_arg(&i, argc, argv);
			if (!val) { fprintf(stderr, "error: --stack requires argument\n"); return -1; }
			out->stack = (uint64_t)strtoul(val, NULL, 0);
			continue;
		}
		if (strncmp(arg, "--memory-budget", 15) == 0 &&
		    (arg[15] == '\0' || arg[15] == '=')) {
			val = cf__next_arg(&i, argc, argv);
			if (!val) { fprintf(stderr, "error: --memory-budget requires argument\n"); return -1; }
			out->memory_budget = (uint64_t)strtoul(val, NULL, 0);
			continue;
		}
		if (strncmp(arg, "--sample-rate", 13) == 0 &&
		    (arg[13] == '\0' || arg[13] == '=')) {
			val = cf__next_arg(&i, argc, argv);
			if (!val) { fprintf(stderr, "error: --sample-rate requires argument\n"); return -1; }
			out->sample_rate = (uint64_t)strtoul(val, NULL, 0);
			continue;
		}
		if (strncmp(arg, "--gc-threshold", 14) == 0 &&
		    (arg[14] == '\0' || arg[14] == '=')) {
			val = cf__next_arg(&i, argc, argv);
			if (!val) { fprintf(stderr, "error: --gc-threshold requires argument\n"); return -1; }
			out->gc_threshold = (uint64_t)strtoul(val, NULL, 0);
			continue;
		}
		if (strncmp(arg, "--plugin", 8) == 0 &&
		    (arg[8] == '\0' || arg[8] == '=')) {
			val = cf__next_arg(&i, argc, argv);
			if (!val) { fprintf(stderr, "error: --plugin requires argument\n"); return -1; }
			if (out->plugin_count < 16) {
				struct cc_plugin_spec *rec = &out->plugin[out->plugin_count++];
				{ cf__kv_t cf__f_[3];
				cf__f_[0].key = "path"; cf__f_[0].dst = (char*)rec->path; cf__f_[0].dstsz = 256U;
				cf__f_[1].key = "name"; cf__f_[1].dst = (char*)rec->name; cf__f_[1].dstsz = 32U;
				cf__f_[2].key = "priority"; cf__f_[2].dst = (char*)rec->priority; cf__f_[2].dstsz = 256U;
				cf__parse_compound(val, cf__f_, 3); }
			}
			continue;
		}
		if (strncmp(arg, "--loader", 8) == 0 &&
		    (arg[8] == '\0' || arg[8] == '=')) {
			val = cf__next_arg(&i, argc, argv);
			if (!val) { fprintf(stderr, "error: --loader requires argument\n"); return -1; }
			(void)val; /* compound: not parseable inline */
			continue;
		}
		if (strncmp(arg, "--plugin-path", 13) == 0 &&
		    (arg[13] == '\0' || arg[13] == '=')) {
			val = cf__next_arg(&i, argc, argv);
			if (!val) { fprintf(stderr, "error: --plugin-path requires argument\n"); return -1; }
			(void)strncpy(out->plugin_path, val, sizeof(out->plugin_path) - 1U);
			continue;
		}
		if (strncmp(arg, "--no-sandbox", 12) == 0 &&
		    (arg[12] == '\0' || arg[12] == '=')) {
			val = cf__next_arg(&i, argc, argv);
			if (!val) { fprintf(stderr, "error: --no-sandbox requires argument\n"); return -1; }
			out->no_sandbox = (strcmp(val,"true")==0||strcmp(val,"yes")==0||
			           strcmp(val,"on")==0||strcmp(val,"1")==0) ? 1 : 0;
			continue;
		}
		if (strncmp(arg, "--plugin-abi", 12) == 0 &&
		    (arg[12] == '\0' || arg[12] == '=')) {
			val = cf__next_arg(&i, argc, argv);
			if (!val) { fprintf(stderr, "error: --plugin-abi requires argument\n"); return -1; }
			out->plugin_abi = (int)strtol(val, NULL, 0);
			continue;
		}
		if (strncmp(arg, "--workers", 9) == 0 &&
		    (arg[9] == '\0' || arg[9] == '=')) {
			val = cf__next_arg(&i, argc, argv);
			if (!val) { fprintf(stderr, "error: --workers requires argument\n"); return -1; }
			out->workers = (uint8_t)strtoul(val, NULL, 0);
			continue;
		}
		if (strcmp(arg, "-w") == 0) {
			val = cf__next_arg(&i, argc, argv);
			if (!val) { fprintf(stderr, "error: --workers requires argument\n"); return -1; }
			out->workers = (uint8_t)strtoul(val, NULL, 0);
			continue;
		}
		if (strncmp(arg, "--thread-sched", 14) == 0 &&
		    (arg[14] == '\0' || arg[14] == '=')) {
			val = cf__next_arg(&i, argc, argv);
			if (!val) { fprintf(stderr, "error: --thread-sched requires argument\n"); return -1; }
			if (strcmp(val, "SCHED_OTHER") == 0) out->thread_sched = CC_sched_pol_SCHED_OTHER;
			else if (strcmp(val, "SCHED_FIFO") == 0) out->thread_sched = CC_sched_pol_SCHED_FIFO;
			else if (strcmp(val, "SCHED_RR") == 0) out->thread_sched = CC_sched_pol_SCHED_RR;
			else { fprintf(stderr, "error: invalid value for --thread-sched: %s\n", val); return -1; }
			continue;
		}
		if (strncmp(arg, "--thread-prio", 13) == 0 &&
		    (arg[13] == '\0' || arg[13] == '=')) {
			val = cf__next_arg(&i, argc, argv);
			if (!val) { fprintf(stderr, "error: --thread-prio requires argument\n"); return -1; }
			out->thread_prio = (uint8_t)strtoul(val, NULL, 0);
			continue;
		}
		if (strncmp(arg, "--cpu-mask", 10) == 0 &&
		    (arg[10] == '\0' || arg[10] == '=')) {
			val = cf__next_arg(&i, argc, argv);
			if (!val) { fprintf(stderr, "error: --cpu-mask requires argument\n"); return -1; }
			out->cpu_mask = (uint64_t)strtoul(val, NULL, 0);
			continue;
		}
		if (out->subcmd == CC_CMD_EVAL) {
			if (strncmp(arg, "--echo", 6) == 0 &&
			    (arg[6] == '\0' || arg[6] == '=')) {
			val = cf__next_arg(&i, argc, argv);
			if (!val) { fprintf(stderr, "error: --echo requires argument\n"); return -1; }
			out->eval.echo = (strcmp(val,"true")==0||strcmp(val,"yes")==0||
			           strcmp(val,"on")==0||strcmp(val,"1")==0) ? 1 : 0;
			continue;
			}
			if (strncmp(arg, "--max-depth", 11) == 0 &&
			    (arg[11] == '\0' || arg[11] == '=')) {
			val = cf__next_arg(&i, argc, argv);
			if (!val) { fprintf(stderr, "error: --max-depth requires argument\n"); return -1; }
			out->eval.max_depth = (uint16_t)strtoul(val, NULL, 0);
			continue;
			}
			if (strncmp(arg, "--profile-out", 13) == 0 &&
			    (arg[13] == '\0' || arg[13] == '=')) {
			val = cf__next_arg(&i, argc, argv);
			if (!val) { fprintf(stderr, "error: --profile-out requires argument\n"); return -1; }
			(void)strncpy(out->eval.profile_out, val, sizeof(out->eval.profile_out) - 1U);
			continue;
			}
		}
		if (out->subcmd == CC_CMD_BENCH) {
			if (strncmp(arg, "--iterations", 12) == 0 &&
			    (arg[12] == '\0' || arg[12] == '=')) {
			val = cf__next_arg(&i, argc, argv);
			if (!val) { fprintf(stderr, "error: --iterations requires argument\n"); return -1; }
			out->bench.iterations = (uint32_t)strtoul(val, NULL, 0);
			continue;
			}
			if (strncmp(arg, "--warmup", 8) == 0 &&
			    (arg[8] == '\0' || arg[8] == '=')) {
			val = cf__next_arg(&i, argc, argv);
			if (!val) { fprintf(stderr, "error: --warmup requires argument\n"); return -1; }
			out->bench.warmup = (uint32_t)strtoul(val, NULL, 0);
			continue;
			}
			if (strncmp(arg, "--report-interval", 17) == 0 &&
			    (arg[17] == '\0' || arg[17] == '=')) {
			val = cf__next_arg(&i, argc, argv);
			if (!val) { fprintf(stderr, "error: --report-interval requires argument\n"); return -1; }
			out->bench.report_interval = (uint64_t)strtoul(val, NULL, 0);
			continue;
			}
		}
		/* pass-through: options for @import namespaces */
		if (strncmp(arg, "--arith.", 8) == 0) { continue; }
		if (strncmp(arg, "--cmp.", 6) == 0) { continue; }
		if (strncmp(arg, "--trig.", 7) == 0) { continue; }
		if (strncmp(arg, "--stats.", 8) == 0) { continue; }
		/* pass-through: --namespace.option for dlopen plugins */
		if (arg[0]=='-' && arg[1]=='-' && strchr(arg+2,'.')!=NULL) { continue; }
		/* positional or unknown option */
		if (arg[0] == '-') {
			fprintf(stderr, "error: unknown option: %s\n", arg);
			return -1;
		}
	}

	return 0;
}

void cc_cmdline_help(void)
{
	fputs("Usage: calctool [OPTIONS] <subcommand>\n", stdout);
	fputs("Plugin-capable expression evaluator\n", stdout);
	fputs("\nOptions:\n", stdout);
	fputs("\n  General:\n", stdout);
	fputs("  -p, --precision            UINT8    Decimal precision used internally by the evaluator.  [default: 12]\n", stdout);
	fputs("  -m, --mode                 ENUM     Top-level evaluation mode (integer, real, or complex).  [default: real]\n", stdout);
	fputs("  -v, --verbosity            ENUM     Verbosity level.  [default: normal]\n", stdout);
	fputs("  -l, --logfile              FILE     Log file path.  [default: \"./calctool.log\"]\n", stdout);
	fputs("  -W, --work-dir             DIR      Working directory for relative-path expressions.  [default: \".\"]\n", stdout);
	fputs("  -C, --config-file          PATH     Optional TOML configuration file path.\n", stdout);
	fputs("      --no-prompt            BOOL     Suppress the interactive prompt in REPL mode.  [default: off]\n", stdout);
	fputs("      --seed                 INT32    PRNG seed. -1 = auto-seed from /dev/urandom.  [default: -1]\n", stdout);
	fputs("      --max-vars             UINT16   Maximum number of user-defined variables.  [default: 256]\n", stdout);
	fputs("      --max-steps            UINT32   Maximum evaluation steps before soft timeout.  [default: 1_000_000]\n", stdout);
	fputs("      --api-token            STRING   API token forwarded to plugins requiring authentication.\n", stdout);
	fputs("      --api-url              STRING   Remote API endpoint used when --api-token is set.  [default: \"https://api.example.com\"]\n", stdout);
	fputs("      --old-mode             STRING   (Deprecated) legacy mode string.\n", stdout);
	fputs("\n  Output:\n", stdout);
	fputs("  -F, --format               ENUM     Result output format.  [default: text]\n", stdout);
	fputs("  -c, --color                BOOL     Force ANSI color even when stdout is not a TTY.  [default: off]\n", stdout);
	fputs("  -j, --json                          Shorthand for --format json.\n", stdout);
	fputs("  -o, --outfile              PATH     Write results to this file instead of stdout.\n", stdout);
	fputs("      --encoding             ENUM     Output character encoding.  [default: utf8]\n", stdout);
	fputs("      --syslog-tag           STRING   Syslog identifier tag.  [default: \"calctool\"]\n", stdout);
	fputs("\n  Performance:\n", stdout);
	fputs("      --deadline             TIME     Soft timeout per evaluation.  [default: 250ms]\n", stdout);
	fputs("      --stack                BYTES    Per-thread stack size for recursive evaluation.  [default: 1MiB]\n", stdout);
	fputs("      --memory-budget        BYTES    Working-set memory budget (advisory; plugins may consult this).  [default: 256MiB]\n", stdout);
	fputs("      --sample-rate          FREQ     Sampling rate for the profiler integration.  [default: 1kHz]\n", stdout);
	fputs("\n  Plugins:\n", stdout);
	fputs("      --plugin               KEY=VAL  Plugin .so to load at startup. Repeat for each plugin.\n", stdout);
	fputs("      --loader               KEY=VAL  Plugin loader settings: sandbox enable + load timeout (ms).\n", stdout);
	fputs("      --plugin-abi           ENUM     Plugin ABI version to enforce.  [default: auto]\n", stdout);
	fputs("\n  Threading:\n", stdout);
	fputs("  -w, --workers              UINT8    Number of packet-processing worker threads.  [default: 4]\n", stdout);
	fputs("      --thread-sched         ENUM     Scheduling policy for worker threads.  [default: SCHED_OTHER]\n", stdout);
	fputs("      --thread-prio          UINT8    Thread priority (only meaningful for SCHED_RR and SCHED_FIFO).  [default: 50]\n", stdout);
	fputs("      --cpu-mask             UINT64   CPU affinity bitmask (hex). 0x0 = no pinning.  [default: 0xFFFF]\n", stdout);
	fputs("      --crypto-key           STRING   AES-256 key for encrypting output (hex string, 64 chars).\n", stdout);
	fputs("  -a, --angle-unit           ENUM     Angle unit for trigonometric functions.  [default: radians]\n", stdout);
	fputs("\narith options (supply as --arith.OPTION=VALUE):\n", stdout);
	fputs("  Arithmetic:\n", stdout);
	fputs("     --arith.div-zero          ENUM     Behaviour when evaluating x / 0.  [default: error]\n", stdout);
	fputs("     --arith.epsilon           DOUBLE   Tolerance below which results are clamped to zero.  [default: 1.0e-9]\n", stdout);
	fputs("     --arith.rounding          ENUM     Rounding rule applied at the end of every binary operation.  [default: nearest]\n", stdout);
	fputs("\ncmp options (supply as --cmp.OPTION=VALUE):\n", stdout);
	fputs("  Comparison:\n", stdout);
	fputs("     --cmp.epsilon           DOUBLE   Floating-point comparison tolerance.  [default: 1.0e-12]\n", stdout);
	fputs("     --cmp.nan-equal         BOOL     Treat NaN as equal to itself for the == operator.  [default: off]\n", stdout);
	fputs("\ntrig options (supply as --trig.OPTION=VALUE):\n", stdout);
	fputs("  Angles:\n", stdout);
	fputs("     --trig.units             ENUM     Unit used to interpret arguments to trig functions.  [default: radians]\n", stdout);
	fputs("     --trig.normalize         BOOL     Reduce input angle modulo 2π before evaluation.  [default: on]\n", stdout);
	fputs("\nstats options (supply as --stats.OPTION=VALUE):\n", stdout);
	fputs("  Sampling:\n", stdout);
	fputs("     --stats.mode              ENUM     Use Bessel-corrected (n-1) divisor or plain n for variance/stddev.  [default: sample]\n", stdout);
	fputs("     --stats.max-points        UINT32   Maximum number of data points accepted by stats functions.  [default: 1_000_000]\n", stdout);
	fputs("     --stats.epsilon           DOUBLE   Tolerance for incremental-mean convergence detection.  [default: 1.0e-10]\n", stdout);
	fputs("\n", stdout);
	fputs("      --help                          Show this help\n", stdout);
	fputs("      --version                       Show version\n", stdout);
	fputs("\nSubcommands:\n", stdout);
	fputs("  eval                         Evaluate one or more expressions\n", stdout);
	fputs("  bench                        Benchmark a plugin under load\n", stdout);
	fputs("  evaluate                     (Deprecated) alias for eval\n", stdout);
}

void cc_cmdline_version(void)
{
	fprintf(stdout, "%s\n", cc__version);
}

void cc_cmdline_dump(const struct cc_cmdline *args)
{
	fprintf(stdout, "crypto-key=***\n");
	fprintf(stdout, "extended-precision=%d\n", args->extended_precision);
	fprintf(stdout, "angle-unit=%ld\n", (long)args->angle_unit);
	fprintf(stdout, "debug-asm=%d\n", args->debug_asm);
	fprintf(stdout, "precision=%ld\n", (long)args->precision);
	fprintf(stdout, "mode=%ld\n", (long)args->mode);
	fprintf(stdout, "verbosity=%ld\n", (long)args->verbosity);
	fprintf(stdout, "logfile=%s\n", args->logfile);
	fprintf(stdout, "work-dir=%s\n", args->work_dir);
	fprintf(stdout, "config-file=%s\n", args->config_file);
	fprintf(stdout, "no-prompt=%d\n", args->no_prompt);
	fprintf(stdout, "locale=%s\n", args->locale);
	fprintf(stdout, "nice=%ld\n", (long)args->nice);
	fprintf(stdout, "rpc-port=%ld\n", (long)args->rpc_port);
	fprintf(stdout, "seed=%ld\n", (long)args->seed);
	fprintf(stdout, "byte-offset=%ld\n", (long)args->byte_offset);
	fprintf(stdout, "max-vars=%ld\n", (long)args->max_vars);
	fprintf(stdout, "max-steps=%ld\n", (long)args->max_steps);
	fprintf(stdout, "feature-flags=%ld\n", (long)args->feature_flags);
	fprintf(stdout, "progress-interval=%g\n", (double)args->progress_interval);
	fprintf(stdout, "epsilon=%g\n", args->epsilon);
	fprintf(stdout, "api-token=***\n");
	fprintf(stdout, "api-url=%s\n", args->api_url);
	fprintf(stdout, "old-mode=%s\n", args->old_mode);
	fprintf(stdout, "format=%ld\n", (long)args->format);
	fprintf(stdout, "color=%d\n", args->color);
	fprintf(stdout, "json=%d\n", args->json);
	fprintf(stdout, "outfile=%s\n", args->outfile);
	fprintf(stdout, "encoding=%ld\n", (long)args->encoding);
	fprintf(stdout, "syslog-tag=%s\n", args->syslog_tag);
	fprintf(stdout, "deadline=%ld\n", (long)args->deadline);
	fprintf(stdout, "stack=%ld\n", (long)args->stack);
	fprintf(stdout, "memory-budget=%ld\n", (long)args->memory_budget);
	fprintf(stdout, "sample-rate=%ld\n", (long)args->sample_rate);
	fprintf(stdout, "gc-threshold=%ld\n", (long)args->gc_threshold);
	fprintf(stdout, "plugin_count=%d\n", args->plugin_count);
	fprintf(stdout, "loader=<compound>\n");
	fprintf(stdout, "plugin-path=%s\n", args->plugin_path);
	fprintf(stdout, "no-sandbox=%d\n", args->no_sandbox);
	fprintf(stdout, "plugin-abi=%ld\n", (long)args->plugin_abi);
	fprintf(stdout, "workers=%ld\n", (long)args->workers);
	fprintf(stdout, "thread-sched=%ld\n", (long)args->thread_sched);
	fprintf(stdout, "thread-prio=%ld\n", (long)args->thread_prio);
	fprintf(stdout, "cpu-mask=%ld\n", (long)args->cpu_mask);
}
