/* Generated by cliforge — DO NOT EDIT */
#ifndef CC_CMDLINE_H
#define CC_CMDLINE_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>

typedef enum cc_subcmd {
	CC_CMD_NONE = 0,
	CC_CMD_EVAL = 1,
	CC_CMD_BENCH = 2,
	CC_CMD_EVALUATE = 3
} cc_subcmd_t;

typedef enum cc_verbosity {
	CC_verbosity_QUIET = 0,
	CC_verbosity_NORMAL = 1,
	CC_verbosity_VERBOSE = 2,
	CC_verbosity_TRACE = 3
} cc_verbosity_t;

typedef enum cc_eval_mode {
	CC_eval_mode_INTEGER = 0,
	CC_eval_mode_REAL = 1,
	CC_eval_mode_COMPLEX = 2
} cc_eval_mode_t;

typedef enum cc_output_fmt {
	CC_output_fmt_TEXT = 0,
	CC_output_fmt_JSON = 1,
	CC_output_fmt_CSV = 2,
	CC_output_fmt_BINARY = 3
} cc_output_fmt_t;

typedef enum cc_sched_pol {
	CC_sched_pol_SCHED_OTHER = 0,
	CC_sched_pol_SCHED_FIFO = 1,
	CC_sched_pol_SCHED_RR = 2
} cc_sched_pol_t;

typedef struct cc_plugin_spec {
	char	path[256];
	char	name[32];
	char	priority[64];
} cc_plugin_spec_t;

struct cc_cmdline {
	cc_subcmd_t subcmd;
	char	crypto_key[64];
	int	extended_precision;
	int	angle_unit;
	int	debug_asm;
	uint8_t	precision;
	cc_eval_mode_t	mode;
	cc_verbosity_t	verbosity;
	char	logfile[256];
	char	work_dir[256];
	char	config_file[256];
	int	no_prompt;
	char	locale[256];
	int8_t	nice;
	int16_t	rpc_port;
	int32_t	seed;
	int64_t	byte_offset;
	uint16_t	max_vars;
	uint32_t	max_steps;
	uint64_t	feature_flags;
	float	progress_interval;
	double	epsilon;
	char	api_token[128];
	char	api_url[256];
	char	old_mode[256];
	cc_output_fmt_t	format;
	int	color;
	int	json;
	char	outfile[256];
	int	encoding;
	char	syslog_tag[32];
	uint64_t	deadline;
	uint64_t	stack;
	uint64_t	memory_budget;
	uint64_t	sample_rate;
	uint64_t	gc_threshold;
	struct cc_plugin_spec	plugin[16];
	int	plugin_count;
	struct {
		int	sandbox;
		uint32_t	timeout;
	} loader;
	char	plugin_path[1024];
	int	no_sandbox;
	int	plugin_abi;
	uint8_t	workers;
	cc_sched_pol_t	thread_sched;
	uint8_t	thread_prio;
	uint64_t	cpu_mask;
	struct {
		int	echo;
		uint16_t	max_depth;
		char	profile_out[256];
	} eval;
	struct {
		uint32_t	iterations;
		uint32_t	warmup;
		uint64_t	report_interval;
		char	plugin_name[32];
	} bench;
	struct {
		char	expressions[32][1024];
		int	expressions_count;
	} evaluate;
};

int  cc_cmdline_parse(int argc, char *const *argv,
                      struct cc_cmdline *out);
void cc_cmdline_help(void);
void cc_cmdline_version(void);
void cc_cmdline_dump(const struct cc_cmdline *args);

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* CC_CMDLINE_H */
