/* ===========================================================================
 *  main_static.c — calctool reference main, static-storage mode
 *  ---------------------------------------------------------------------------
 *
 *  Illustrative consumer of the (hypothetical, yet-to-be-generated) cliforge
 *  outputs. The generator will produce:
 *
 *      cmdline.h / cmdline.c               (from calctool.cf)
 *      cmdline_arith.h / cmdline_arith.c   (from lib/arith.cf)
 *      cmdline_cmp.h   / cmdline_cmp.c
 *      cmdline_trig.h  / cmdline_trig.c    (when -D have-trig)
 *      cmdline_stats.h / cmdline_stats.c   (when -D have-stats)
 *      cmdline_plug.h  / cmdline_plug.c    (from lib/plugin_api.cf)
 *
 *  This file demonstrates the *passive* API contract: parse argv into a
 *  caller-owned struct, inspect resolved values, hand per-alias argv
 *  slices to each library's own parser, optionally dlopen plugins.
 *
 *  Build (once the generator exists):
 *      cc -std=c99 -Wall -Wextra -O2 \
 *         main_static.c cmdline.c cmdline_arith.c cmdline_cmp.c \
 *         cmdline_plug.c -ldl -o calctool
 * ========================================================================== */

#include "cmdline.h"          /* generated by cliforge from calctool.cf */
#include "cmdline_arith.h"
#include "cmdline_cmp.h"
#include "cmdline_plug.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <dlfcn.h>            /* dlopen, dlsym, dlclose */

/* ---------------------------------------------------------------------------
 *  Plugin entry-point convention.
 *
 *  cliforge does not impose this — the application author defines it. Every
 *  .so dlopen'd by calctool is expected to export one symbol:
 *
 *      int my_plugin_parse(int argc, char **argv, void *opaque_state);
 *
 *  The plugin internally calls plug_cmdline_parse_slice(...) (generated by
 *  cliforge from plugin_api.cf) and then runs its own initialization.
 * ------------------------------------------------------------------------- */
typedef int (*plugin_parse_fn)(int argc, char **argv, void *state);

/* ---------------------------------------------------------------------------
 *  helpers
 * ------------------------------------------------------------------------- */

static void die(const char *msg, int rc)
{
    fprintf(stderr, "calctool: %s\n", msg);
    exit(rc < 0 ? -rc : 1);
}

static const char *verbosity_name(enum cc_verbosity v)
{
    /* cc_verbosity_to_str() is generated by cliforge */
    return cc_verbosity_to_str(v);
}

/* ---------------------------------------------------------------------------
 *  per-plugin loading
 * ------------------------------------------------------------------------- */

static int load_one_plugin(const struct cc_plugin *spec,
                            const struct cc_args   *app_args)
{
    void *h = dlopen(spec->path, RTLD_NOW | RTLD_LOCAL);
    if (h == NULL) {
        fprintf(stderr, "calctool: dlopen(%s) failed: %s\n",
                spec->path, dlerror());
        return -1;
    }

    /* Convention: every plugin exports <name>_parse */
    char symbol[64];
    (void)snprintf(symbol, sizeof symbol, "%s_parse", spec->name);

    plugin_parse_fn parse = (plugin_parse_fn)dlsym(h, symbol);
    if (parse == NULL) {
        fprintf(stderr, "calctool: plugin %s missing symbol %s\n",
                spec->name, symbol);
        dlclose(h);
        return -1;
    }

    /* Hand the per-alias argv slice to the plugin. The slice is built by
     * the generated app parser: it collected all --<spec->name>.* tokens
     * during cc_cmdline_parse() above. */
    char **slice;
    size_t slice_count;
    if (cc_cmdline_get_slice(app_args, spec->name, &slice, &slice_count) != 0) {
        slice = NULL; slice_count = 0;        /* no options for this plugin */
    }

    if (parse((int)slice_count, slice, /*plugin state*/ NULL) != 0) {
        fprintf(stderr, "calctool: plugin %s rejected its options\n",
                spec->name);
        dlclose(h);
        return -1;
    }
    /* Intentionally leak `h`: keep it open for the lifetime of the run. */
    return 0;
}

/* ---------------------------------------------------------------------------
 *  main
 * ------------------------------------------------------------------------- */

int main(int argc, char **argv)
{
    /* -----------------------------------------------------------------
     *  Stage 1 — parse the application's own surface.
     *
     *  cc_cmdline_parse():
     *    - splices any -C/@ response files into argv
     *    - dispatches to the matching subcommand (eval / bench)
     *    - validates ranges, group constraints, required fields
     *    - splits per-alias slices for imported libs
     * ----------------------------------------------------------------- */
    struct cc_args args;
    int rc = cc_cmdline_parse(argc, argv, &args);
    if (rc != 0) {
        die(args.cliforge_error_msg, rc);
    }

    if (args.verbose >= CC_VERBOSITY_VERBOSE) {
        printf("verbosity      : %s\n", verbosity_name(args.verbose));
        printf("precision      : %u\n", args.precision);
        printf("logfile        : %s\n", args.logfile);
    }

    /* -----------------------------------------------------------------
     *  Stage 2 — convert quantity types when you need the number.
     *  Storage is {value, unit}; conversion happens here, not at parse.
     * ----------------------------------------------------------------- */
    uint64_t deadline_ns = cc_duration_to_ns(&args.deadline);
    uint64_t stack_bytes = cc_bytes_to_B   (&args.stack);
    if (args.verbose >= CC_VERBOSITY_VERBOSE) {
        printf("deadline       : %llu ns\n", (unsigned long long)deadline_ns);
        printf("stack          : %llu B\n",  (unsigned long long)stack_bytes);
    }

    /* -----------------------------------------------------------------
     *  Stage 3 — hand per-alias slices to statically-linked libs.
     *  Each lib's generated parser owns its own validation.
     * ----------------------------------------------------------------- */
    struct arith_args arith_args;
    char **slice; size_t n_slice;
    if (cc_cmdline_get_slice(&args, "arith", &slice, &n_slice) == 0) {
        if (arith_cmdline_parse_slice(slice, n_slice, &arith_args) != 0) {
            die(arith_args.cliforge_error_msg, -1);
        }
    }

    struct cmp_args cmp_args;
    if (cc_cmdline_get_slice(&args, "cmp", &slice, &n_slice) == 0) {
        if (cmp_cmdline_parse_slice(slice, n_slice, &cmp_args) != 0) {
            die(cmp_args.cliforge_error_msg, -1);
        }
    }

    /* -----------------------------------------------------------------
     *  Stage 4 — load dlopen'd plugins. Each gets its own argv slice.
     *  args.plugin is a fixed-size array of cc_plugin (static mode).
     * ----------------------------------------------------------------- */
    for (size_t i = 0; i < args.plugin_count; i++) {
        if (load_one_plugin(&args.plugin[i], &args) != 0) {
            /* policy: fail soft for plugins, hard for static libs */
            fprintf(stderr, "calctool: continuing without plugin %s\n",
                    args.plugin[i].name);
        }
    }

    /* -----------------------------------------------------------------
     *  Stage 5 — dispatch on the subcommand.
     * ----------------------------------------------------------------- */
    switch (cc_cmdline_subcommand(&args)) {
    case CC_CMD_EVAL: {
        for (size_t i = 0; i < args.eval.expressions_count; i++) {
            if (args.eval.echo) {
                printf("> %s\n", args.eval.expressions[i]);
            }
            /* … run evaluator on args.eval.expressions[i] … */
        }
        break;
    }
    case CC_CMD_BENCH: {
        printf("benchmarking %s: %u iterations\n",
               args.bench.plugin_name, args.bench.iterations);
        /* … bench loop … */
        break;
    }
    case CC_CMD_NONE:
    default:
        cc_cmdline_print_help(stdout, NULL);
        break;
    }

    /* No-op in static mode, future-compatible. */
    cc_cmdline_free(&args);
    return 0;
}
