/* Generated by cliforge — DO NOT EDIT */
#include "cmdline_arith.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* ------- internal helpers ------- */
typedef struct { const char *key; char *dst; unsigned int dstsz; } cf__kv_t;

static const char *cf__next_arg(int *i, int argc, char *const *argv)
{
	const char *arg = argv[*i];
	const char *eq  = strchr(arg, '=');
	if (eq != NULL) return eq + 1;
	if (*i + 1 < argc && argv[*i + 1][0] != '-') { (*i)++; return argv[*i]; }
	return NULL;
}

static const char arith__version[] = "arith 0.0.0";

int arith_cmdline_parse(int argc, char *const *argv,
                     struct arith_cmdline *out)
{
	int i;
	const char *arg;
	const char *val;

	(void)memset(out, 0, sizeof(*out));
	out->div_zero = ARITH_div_zero_policy_ERROR;
	out->epsilon = 1.0e-9;
	out->rounding = 0; /* default: nearest */

	/* --- main option parse loop --- */
	for (i = 1; i < argc; i++) {
		arg = argv[i];
		val = NULL;

		/* skip subcommand token */
		if (arg[0] != '-') continue;

		/* --help */
		if (strcmp(arg, "--help") == 0 || strcmp(arg, "-h") == 0) {
			arith_cmdline_help();
			return 1;
		}
		/* --version */
		if (strcmp(arg, "--version") == 0) {
			arith_cmdline_version();
			return 1;
		}

		if (strncmp(arg, "--div-zero", 10) == 0 &&
		    (arg[10] == '\0' || arg[10] == '=')) {
			val = cf__next_arg(&i, argc, argv);
			if (!val) { fprintf(stderr, "error: --div-zero requires argument\n"); return -1; }
			if (strcmp(val, "nan") == 0) out->div_zero = ARITH_div_zero_policy_NAN;
			else if (strcmp(val, "inf") == 0) out->div_zero = ARITH_div_zero_policy_INF;
			else if (strcmp(val, "error") == 0) out->div_zero = ARITH_div_zero_policy_ERROR;
			else if (strcmp(val, "saturate") == 0) out->div_zero = ARITH_div_zero_policy_SATURATE;
			else { fprintf(stderr, "error: invalid value for --div-zero: %s\n", val); return -1; }
			continue;
		}
		if (strncmp(arg, "--epsilon", 9) == 0 &&
		    (arg[9] == '\0' || arg[9] == '=')) {
			val = cf__next_arg(&i, argc, argv);
			if (!val) { fprintf(stderr, "error: --epsilon requires argument\n"); return -1; }
			out->epsilon = strtod(val, NULL);
			continue;
		}
		if (strncmp(arg, "--rounding", 10) == 0 &&
		    (arg[10] == '\0' || arg[10] == '=')) {
			val = cf__next_arg(&i, argc, argv);
			if (!val) { fprintf(stderr, "error: --rounding requires argument\n"); return -1; }
			out->rounding = (int)strtol(val, NULL, 0);
			continue;
		}
		/* pass-through: --namespace.option for dlopen plugins */
		if (arg[0]=='-' && arg[1]=='-' && strchr(arg+2,'.')!=NULL) { continue; }
		/* positional or unknown option */
		if (arg[0] == '-') {
			fprintf(stderr, "error: unknown option: %s\n", arg);
			return -1;
		}
	}

	return 0;
}

void arith_cmdline_help(void)
{
	fputs("Usage: arith [OPTIONS]\n", stdout);
	fputs("Basic arithmetic operators (+, -, *, /)\n", stdout);
	fputs("\nOptions:\n", stdout);
	fputs("\n  Arithmetic:\n", stdout);
	fputs("      --div-zero             ENUM     Behaviour when evaluating x / 0.  [default: error]\n", stdout);
	fputs("      --epsilon              DOUBLE   Tolerance below which results are clamped to zero.  [default: 1.0e-9]\n", stdout);
	fputs("      --rounding             ENUM     Rounding rule applied at the end of every binary operation.  [default: nearest]\n", stdout);
	fputs("      --help                          Show this help\n", stdout);
	fputs("      --version                       Show version\n", stdout);
}

void arith_cmdline_version(void)
{
	fprintf(stdout, "%s\n", arith__version);
}

void arith_cmdline_dump(const struct arith_cmdline *args)
{
	fprintf(stdout, "div-zero=%ld\n", (long)args->div_zero);
	fprintf(stdout, "epsilon=%g\n", args->epsilon);
	fprintf(stdout, "rounding=%ld\n", (long)args->rounding);
}
