/* Generated by cliforge — DO NOT EDIT */
#ifndef ARITH_CMDLINE_H
#define ARITH_CMDLINE_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>

typedef enum arith_div_zero_policy {
	ARITH_div_zero_policy_NAN = 0,
	ARITH_div_zero_policy_INF = 1,
	ARITH_div_zero_policy_ERROR = 2,
	ARITH_div_zero_policy_SATURATE = 3
} arith_div_zero_policy_t;

struct arith_cmdline {
	arith_div_zero_policy_t	div_zero;
	double	epsilon;
	int	rounding;
};

int  arith_cmdline_parse(int argc, char *const *argv,
                      struct arith_cmdline *out);
void arith_cmdline_help(void);
void arith_cmdline_version(void);
void arith_cmdline_dump(const struct arith_cmdline *args);

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* ARITH_CMDLINE_H */
