/* Generated by cliforge — DO NOT EDIT */
#ifndef STATS_CMDLINE_H
#define STATS_CMDLINE_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>

typedef enum stats_sampling_mode {
	STATS_sampling_mode_SAMPLE = 0,
	STATS_sampling_mode_POPULATION = 1
} stats_sampling_mode_t;

struct stats_cmdline {
	stats_sampling_mode_t	mode;
	uint32_t	max_points;
	double	epsilon;
};

int  stats_cmdline_parse(int argc, char *const *argv,
                      struct stats_cmdline *out);
void stats_cmdline_help(void);
void stats_cmdline_version(void);
void stats_cmdline_dump(const struct stats_cmdline *args);

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* STATS_CMDLINE_H */
