/* Generated by cliforge — DO NOT EDIT */
#include "cmdline_stats.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* ------- internal helpers ------- */
typedef struct { const char *key; char *dst; unsigned int dstsz; } cf__kv_t;

static const char *cf__next_arg(int *i, int argc, char *const *argv)
{
	const char *arg = argv[*i];
	const char *eq  = strchr(arg, '=');
	if (eq != NULL) return eq + 1;
	if (*i + 1 < argc && argv[*i + 1][0] != '-') { (*i)++; return argv[*i]; }
	return NULL;
}

static const char stats__version[] = "stats 0.0.0";

int stats_cmdline_parse(int argc, char *const *argv,
                     struct stats_cmdline *out)
{
	int i;
	const char *arg;
	const char *val;

	(void)memset(out, 0, sizeof(*out));
	out->mode = STATS_sampling_mode_SAMPLE;
	out->max_points = 1000000; /* 1_000_000 */
	out->epsilon = 1.0e-10;

	/* --- main option parse loop --- */
	for (i = 1; i < argc; i++) {
		arg = argv[i];
		val = NULL;

		/* skip subcommand token */
		if (arg[0] != '-') continue;

		/* --help */
		if (strcmp(arg, "--help") == 0 || strcmp(arg, "-h") == 0) {
			stats_cmdline_help();
			return 1;
		}
		/* --version */
		if (strcmp(arg, "--version") == 0) {
			stats_cmdline_version();
			return 1;
		}

		if (strncmp(arg, "--mode", 6) == 0 &&
		    (arg[6] == '\0' || arg[6] == '=')) {
			val = cf__next_arg(&i, argc, argv);
			if (!val) { fprintf(stderr, "error: --mode requires argument\n"); return -1; }
			if (strcmp(val, "sample") == 0) out->mode = STATS_sampling_mode_SAMPLE;
			else if (strcmp(val, "population") == 0) out->mode = STATS_sampling_mode_POPULATION;
			else { fprintf(stderr, "error: invalid value for --mode: %s\n", val); return -1; }
			continue;
		}
		if (strncmp(arg, "--max-points", 12) == 0 &&
		    (arg[12] == '\0' || arg[12] == '=')) {
			val = cf__next_arg(&i, argc, argv);
			if (!val) { fprintf(stderr, "error: --max-points requires argument\n"); return -1; }
			out->max_points = (uint32_t)strtoul(val, NULL, 0);
			continue;
		}
		if (strncmp(arg, "--epsilon", 9) == 0 &&
		    (arg[9] == '\0' || arg[9] == '=')) {
			val = cf__next_arg(&i, argc, argv);
			if (!val) { fprintf(stderr, "error: --epsilon requires argument\n"); return -1; }
			out->epsilon = strtod(val, NULL);
			continue;
		}
		/* pass-through: --namespace.option for dlopen plugins */
		if (arg[0]=='-' && arg[1]=='-' && strchr(arg+2,'.')!=NULL) { continue; }
		/* positional or unknown option */
		if (arg[0] == '-') {
			fprintf(stderr, "error: unknown option: %s\n", arg);
			return -1;
		}
	}

	return 0;
}

void stats_cmdline_help(void)
{
	fputs("Usage: stats [OPTIONS]\n", stdout);
	fputs("Statistics ops (mean, stddev, variance, median, ...)\n", stdout);
	fputs("\nOptions:\n", stdout);
	fputs("\n  Sampling:\n", stdout);
	fputs("      --mode                 ENUM     Use Bessel-corrected (n-1) divisor or plain n for variance/stddev.  [default: sample]\n", stdout);
	fputs("      --max-points           UINT32   Maximum number of data points accepted by stats functions.  [default: 1_000_000]\n", stdout);
	fputs("      --epsilon              DOUBLE   Tolerance for incremental-mean convergence detection.  [default: 1.0e-10]\n", stdout);
	fputs("      --help                          Show this help\n", stdout);
	fputs("      --version                       Show version\n", stdout);
}

void stats_cmdline_version(void)
{
	fprintf(stdout, "%s\n", stats__version);
}

void stats_cmdline_dump(const struct stats_cmdline *args)
{
	fprintf(stdout, "mode=%ld\n", (long)args->mode);
	fprintf(stdout, "max-points=%ld\n", (long)args->max_points);
	fprintf(stdout, "epsilon=%g\n", args->epsilon);
}
